### ISSUE TITLE
CompileError: command gcc.exe' failed with exit status 1

### ISSUE THREAD

**Issue by Kingflyinger** [stan-dev/pystan2#562]
i got a problem and i have tried many ways but not works

windows
Python 3.7.1
x86_64-w64-mingw32 
gcc version 5.3.0 (Rev5, Built by MSYS2 project)
pystan 2.18.0.0

CompileError: command gcc.exe' failed with exit status 1

`
>>>import pystan
>>> model_code = 'parameters {real y;} model {y ~ normal(0,1);}'
>>> model = pystan.StanModel(model_code=model_code)`

#### Current Output:
`### INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
D:\Anaconda3\lib\site-packages\Cython\Compiler\Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: D:\MyConfiguration\yiheng.liu\AppData\Local\Temp\tmp9sxhj0sc\stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_1375052828112762571.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
Traceback (most recent call last):

  File "<ipython-input-1-973d9bffecdb>", line 3, in <module>
    model = pystan.StanModel(model_code=model_code)

  File "D:\Anaconda3\lib\site-packages\pystan\model.py", line 350, in __init__
    build_extension.run()

  File "D:\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()

  File "D:\Anaconda3\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()

  File "D:\Anaconda3\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)

  File "D:\Anaconda3\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)

  File "D:\Anaconda3\lib\distutils\ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)

  File "D:\Anaconda3\lib\distutils\cygwinccompiler.py", line 175, in _compile
    raise CompileError(msg)

CompileError: command 'D:\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1`

i have changes distutils.cfg
install by conda-forge

**Comment by ahartikainen** [comment]
Have you installed `libpython` too?

Also try install with pip

    conda install libpython

    conda uninstall pystan
    pip install pystan

**Comment by Kingflyinger** [comment]
I installed libpython ,
and I once tried to install by pip,but it raise errors

**Comment by Kingflyinger** [comment]
> Have you installed libpython too?
> Also try install with pip
> conda install libpython
> 
> conda uninstall pystan
> pip install pystan

I installed libpython ,
and I once tried to install by pip,but it raise errors

**Comment by Kingflyinger** [comment]
when I install it with pip
it raises error like it 

`Command "D:\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='D:\\MyConfiguration\\yiheng.liu\\AppData\\Local\\Temp\\pip-install-o8j0udut\\pystan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record D:\MyConfiguration\yiheng.liu\AppData\Local\Temp\pip-record-t0j3cf0p\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in D:\MyConfiguration\yiheng.liu\AppData\Local\Temp\pip-install-o8j0udut\pystan\`

**Comment by ahartikainen** [comment]
Ok, that would suggest that there is some issue with compiler.

Can you create a new conda environment and follow all the steps in https://pystan.readthedocs.io/en/latest/windows.html

Remember to install libpython and m2w64-toolchain.

**Comment by Ritz111** [comment]
> Have you installed `libpython` too?
> 
> Also try install with pip
> 
> ```
> conda install libpython
> 
> conda uninstall pystan
> pip install pystan
> ```

Hi, it raised errors when I tried to re-install pystan by pip, like this:
```
    running build_ext
    Building msvcr library: "c:\users\ritz\appdata\local\continuum\anaconda2\libs\libmsvcr90.a" (from C:\WINDOWS\winsxs\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9415_none_08e0c10ba840a28a\msvcr90.dll)
    objdump.exe: C:\WINDOWS\winsxs\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9415_none_08e0c10ba840a28a\msvcr90.dll: File format not recognized
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\ritz\appdata\local\temp\pip-install-6q4dqr\pystan\setup.py", line 255, in <module>
        setup_package()
      File "c:\users\ritz\appdata\local\temp\pip-install-6q4dqr\pystan\setup.py", line 244, in setup_package
        dist.run_commands()
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\distutils\command\build_ext.py", line 309, in run
        force=self.force)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\site-packages\numpy\distutils\ccompiler.py", line 765, in new_compiler
        compiler = klass(None, dry_run, force)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 106, in __init__
        msvcr_success = build_msvcr_library()
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 398, in build_msvcr_library
        generate_def(dll_file, def_file)
      File "c:\users\ritz\appdata\local\continuum\anaconda2\lib\site-packages\numpy\distutils\mingw32ccompiler.py", line 301, in generate_def
        raise ValueError("Symbol table not found")
    ValueError: Symbol table not found
```
What it means? 
How to solve it?
THANKS~

**Comment by Kingflyinger** [comment]
> Ok, that would suggest that there is some issue with compiler.
> Can you create a new conda environment and follow all the steps in https://pystan.readthedocs.io/en/latest/windows.html
> Remember to install libpython and m2w64-toolchain.

thanks a lot,after i create a new env and follow your instructions ,it works at last.
In general I don`t like create new env on my computer,but it seems like create new env and follow instructions can make sense in most cases

**Comment by MGES** [comment]
I also met this problem.

**Comment by MGES** [comment]
> Ok, that would suggest that there is some issue with compiler.
> 
> Can you create a new conda environment and follow all the steps in https://pystan.readthedocs.io/en/latest/windows.html
> 
> Remember to install libpython and m2w64-toolchain.

I use this way,
but also met this problem.
