### ISSUE TITLE
pip3 install pystan 2.19  error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by derekwilliamscrosswinds** [stan-dev/pystan2#656]
#### Summary:
While pip installing into a Centos8 docker container, pystan throws the following error

```
Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ionolzru/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jyxo24pk-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/fbprophet
    creating build/lib/fbprophet/stan_model
    INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_861b75c6337e237650a61ae58c4385ef NOW.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ionolzru/fbprophet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jyxo24pk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ionolzru/fbprophet/
```

### GCC Version
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)
```

**Comment by derekwilliamscrosswinds** [comment]
I think I should have opened this with the fbprophet team. I was so focused on solving what seemed to be a pystan problem.

**Comment by ahartikainen** [comment]
It is probably a PyStan issue. Is the compiler C++14 compatible?

**Comment by derekwilliamscrosswinds** [comment]
GCC 8.2.1 should be compatible with c++2a features. As I am not a C++ developer, it's hard for me to say if pystan will work on c++2a. It appears to work on C++17 as it works on Amazon Linux out of the box. However, to put this into a container would mean compiling GCC 7.3 into a container which will leave me with a 7GB container (we have done this before)

**Comment by ahartikainen** [comment]
I think your compiler should be fine.

Can you try to install pystan from the source?

    git clone --recursive https://github.com/stan-dev/pystan
    cd pystan
    python3 -m pip install . -vvvv

And see if there is any errors?

**Comment by ahartikainen** [comment]
Also, how much do you have RAM?

**Comment by derekwilliamscrosswinds** [comment]
@ahartikainen I have 16GB on my local machine and 32GB on our build agents.

That command failed as well. Here's the log
```
building 'pystan._api' extension
    Warning: Can't read registry to find the necessary compiler setting
    Make sure that Python modules winreg, win32api or win32con are installed.
    C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC

    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/pystan
    creating build/temp.linux-x86_64-3.6/pystan/stan
    creating build/temp.linux-x86_64-3.6/pystan/stan/src
    creating build/temp.linux-x86_64-3.6/pystan/stan/src/stan
    creating build/temp.linux-x86_64-3.6/pystan/stan/src/stan/lang
    creating build/temp.linux-x86_64-3.6/pystan/stan/src/stan/lang/grammars
compile options: '-DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -I./pystan -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.69.0 -Ipystan/stan/lib/stan_math/lib/sundials_4.1.0/include -I/usr/include/python3.6m -c'
    extra options: '-Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y'
    gcc: pystan/stan/src/stan/lang/ast_def.cpp
    gcc: pystan/_api.cpp
    gcc: pystan/stan/src/stan/lang/grammars/bare_type_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/block_var_decls_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/expression07_grammar_inst.cpp
    gcc: pystan/stan/src/stan/lang/grammars/expression_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/functions_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/indexes_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/local_var_decls_grammar_inst.cpp
    gcc: pystan/stan/src/stan/lang/grammars/program_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/semantic_actions_def.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/statement_2_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/term_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/whitespace_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: pystan/stan/src/stan/lang/grammars/statement_grammar_inst.cpp
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
    error: Command "gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DBOOST_DISABLE_ASSERTS -DBOOST_NO_DECLTYPE -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -DBOOST_RESULT_OF_USE_TR1 -DFUSION_MAX_VECTOR_SIZE=12 -I./pystan -Ipystan/stan/src -Ipystan/stan/lib/stan_math/ -Ipystan/stan/lib/stan_math/lib/eigen_3.3.3 -Ipystan/stan/lib/stan_math/lib/boost_1.69.0 -Ipystan/stan/lib/stan_math/lib/sundials_4.1.0/include -I/usr/include/python3.6m -c pystan/stan/src/stan/lang/ast_def.cpp -o build/temp.linux-x86_64-3.6/pystan/stan/src/stan/lang/ast_def.o -Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y" failed with exit status 1
    Running setup.py install for pystan: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-vj4g5env-build
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-vj4g5env-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jr3qc_ei-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-vj4g5env-build/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 882, in install
    spinner=spinner,
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 717, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-vj4g5env-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-jr3qc_ei-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-vj4g5env-build/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.python.org
https://pypi.python.org:443 "GET /pypi/pip/json HTTP/1.1" 301 122
Updating cache with response from "https://pypi.python.org/pypi/pip/json"
Caching permanant redirect
Looking up "https://pypi.org/pypi/pip/json" in the cache
No cache entry available
Starting new HTTPS connection (1): pypi.org
https://pypi.org:443 "GET /pypi/pip/json HTTP/1.1" 200 19903
Updating cache with response from "https://pypi.org/pypi/pip/json"
Caching due to etag
The command '/bin/sh -c git clone --recursive https://github.com/stan-dev/pystan     && cd pystan     && python3 -m pip install . -vvvv' returned a non-zero code: 1
```

**Comment by derekwilliamscrosswinds** [comment]
any ideas on this? This is quickly going to become a production issue soon.

**Comment by riddell-stan** [comment]
It looks like it is not finding your compiler:

```
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
```

**Comment by joyjo** [comment]
i have same problem, so is there anyone who can solved this problem?

**Comment by ahartikainen** [comment]
Hi, can you call

    gcc --version

If you can, then can you define `CC` and `CXX` (or add the lines in `.bashrc`)

    export CC="gcc"
    export CXX="g++"

**Comment by joyjo** [comment]
hi, thank you for quick reply.

gcc version is 6.5.0. 

after defined `CC` and `CXX`

```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    model = pystan.StanModel(model_code=model_code)  # this will take a minute
  File "/lib/python3.6/site-packages/pystan/model.py", line 378, in __init__
    build_extension.run()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 4
```

**Comment by ahartikainen** [comment]
Hi, do you run your code in Jupyter? Can you check if there is an error message for C++?

otherwise use `pystan.Stanmodel(..., verbose=True)` to see C++ error messages.

**Comment by joyjo** [comment]
No, i do not use Jupyter.

after add `verbose=True`,  error message:
`gcc: internal compiler error: Killed (program cc1plus)`

**Comment by ahartikainen** [comment]
Is there anything before that?

**Comment by joyjo** [comment]
this full outputs
```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_5944b02c79788fa0db5b3a93728ca2bf NOW.
INFO:pystan:OS: linux, Python: 3.6.10 (default, Dec 19 2019, 23:04:32) 
[GCC 5.4.0 20160609], Cython 0.29.20
Compiling /tmp/pystan_oe27z_2q/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_9011524188136239038.pyx because it changed.
[1/1] Cythonizing /tmp/pystan_oe27z_2q/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_9011524188136239038.pyx
building 'stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_9011524188136239038' extension
creating /tmp/pystan_oe27z_2q/tmp
creating /tmp/pystan_oe27z_2q/tmp/pystan_oe27z_2q
gcc -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I/tmp/pystan_oe27z_2q -I/lib/python3.6/site-packages/pystan -I/lib/python3.6/site-packages/pystan -I/lib/python3.6/site-packages/pystan/stan/src -I/lib/python3.6/site-packages/pystan/stan/lib/stan_math -I/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3 -I/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/boost_1.69.0 -I/lib/python3.6/site-packages/pystan/stan/lib/stan_math/lib/sundials_4.1.0/include -I/lib/python3.6/site-packages/numpy/core/include -I/include -I/usr/include/python3.6m -c /tmp/pystan_oe27z_2q/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_9011524188136239038.cpp -o /tmp/pystan_oe27z_2q/tmp/pystan_oe27z_2q/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_9011524188136239038.o -O2 -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y
In file included from /lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /tmp/pystan_oe27z_2q/stanfit4anon_model_5944b02c79788fa0db5b3a93728ca2bf_9011524188136239038.cpp:693:
/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    model = pystan.StanModel(model_code=model_code, verbose=True)  # this will take a minute
  File "/lib/python3.6/site-packages/pystan/model.py", line 378, in __init__
    build_extension.run()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 4
```

**Comment by ahartikainen** [comment]
How much do you have RAM? This might mean that your RAM gets full and gcc then kills the process.

Can you try to add

    StanModel(..., verbose=True, extra_compile_args=["-flto"])

**Comment by joyjo** [comment]
I think, the problem was RAM size.  How much RAM required for working pystan?

**Comment by ahartikainen** [comment]
I think at least 2GB (4 doesn't hurt).

lto trick might compile with less than 2. (e.g. I have used it in Google Colab)
