### ISSUE TITLE
PyStan Failure With `n_jobs != 1`, Python 3.8, Mac OS X

### ISSUE THREAD

**Issue by farr** [stan-dev/pystan2#693]
#### Summary:
When trying to run more than one core for sampling on Mac OS X Catalina (10.15.4) and Python 3.8, PyStan returns an error that is presumably related to pickling and transfer of the model to the fork-ed processes.

#### Description:
The attached directory includes a conda environment with Python 3.8 and pystan (nothing else); running 
```bash
python fail.py
```
gives the following error:
```
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_bb6ff6b843123208aa1c7d673897c607 NOW.
Process SpawnPoolWorker-4:
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_bb6ff6b843123208aa1c7d673897c607_3937439003679922443'
Traceback (most recent call last):
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_bb6ff6b843123208aa1c7d673897c607_3937439003679922443'
Traceback (most recent call last):
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_bb6ff6b843123208aa1c7d673897c607_3937439003679922443'
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/wfarr/anaconda3/envs/stan-fails/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_bb6ff6b843123208aa1c7d673897c607_3937439003679922443'
```

A similar error *does not* occur in Python 3.7.  Perhaps the default Pickle version changed in 3.8, and it's breaking the way that PyStan sends models to the multiprocessing processes for sampling?

#### Reproducible Steps:
See above.

#### PyStan Version:
2.19.1.1

#### Python Version:
3.8.2

#### Operating System:
Mac OS X Catalina (10.15.4)
[stan-fails.tar.gz](https://github.com/stan-dev/pystan/files/4430551/stan-fails.tar.gz)

**Comment by ahartikainen** [comment]
https://twitter.com/raymondh/status/1180209729609420800?s=19

"#Python 3.8 news:  The multiprocessing module now uses spawn() instead of fork() to avoid forking limitations on macOS. Accordingly, https://t.co/tC79sePQXo() and its variants should only be applied to functions defined in other modules (not __main__) so they can be pickled."

**Comment by defjaf** [comment]
Not fixed by the wheels, I don't think (actually I'm not sure if this is the case since pip seems to be building the wheel on my macOS Catalina/py3.8 setup). Any plans/hopes for a fix?

I admit I don't know enough about `multiprocessing` and `cython` to be able to tell if this is a straightforward fix or quite difficult (I fear the latter since I think this might be same thing that is keeping `pystan` + `multiprocessing` from working on Windows).

**Comment by aapeliv** [comment]
I'm getting similar errors trying to run the getting started tutorial on Mojave and homebrew python3.8. Adding `n_jobs=1` to the `sm.sampling` call makes it work.

**Comment by ahartikainen** [comment]
Can you try add this before imports

```
import multiprocessing
multiprocessing.set_start_method("fork")
```
https://discourse.mc-stan.org/t/pystan-throws-error-when-running-chains-in-parallel-n-jobs-1/17563/4

**Comment by aapeliv** [comment]
> Can you try add this before imports

Yep, that works.

**Comment by morganstrom** [comment]
Thanks for a very helpful thread! I had the same issue and @ahartikainen 's solution fixed it for me
