### ISSUE TITLE
distutils.errors.CompileError: command 'gcc' terminated by signal 6

### ISSUE THREAD

**Issue by idumahg** [stan-dev/pystan2#714]
#### Summary:
I am trying to run a regression model, and I get the error that command 'gcc' terminated by signal 6

#### Description:
The error I get is detailed as:
distutils.errors.CompileError: command 'gcc' terminated by signal 6
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file

#### Reproducible Steps:
import pystan
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

sns.set()  # creates nice plot aesthetic
np.random.seed(101)

model = """
data {
    int<lower=0> N;
    vector[N] x;
    vector[N] y;
}
parameters {
    real alpha;
    real beta;
    real<lower=0> sigma;
}
model {
    y ~ normal(alpha + beta * x, sigma);
}
"""

"""Data generation, the ground truth"""
alpha = 4.0
beta = 0.5
sigma = 1.0

x = 10 * np.random.rand(100)
y = alpha + beta * x
y = np.random.normal(y, scale=sigma)  # generates data according to y ~ N(alpha+beta*X, sigma)
plt.scatter(x, y)
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.title('Scatter Plot of Data')

plt.show()

data = {'N': len(x), 'x': x, 'y': y}

sm = pystan.StanModel(model_code=model)

fit = sm.sampling(data=data, iter=1000, chains=4, warmup=500, thin=1, seed=101)
print(fit)

#### Current Output:
The current output. Knowing what is the current behavior is useful.
/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/bin/python /Users/gideonidumah/Desktop/Internship/msgi_2020_gideon/MJHS_model/practice.py
INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_cb4cc9c2a04d0e34d711077557307fb7 NOW.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
Traceback (most recent call last):
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/distutils/unixccompiler.py", line 117, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/distutils/spawn.py", line 147, in _spawn_posix
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'gcc' terminated by signal 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gideonidumah/Desktop/Internship/msgi_2020_gideon/MJHS_model/practice.py", line 48, in <module>
    sm = pystan.StanModel(model_code=model)
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/site-packages/pystan/model.py", line 450, in __init__
    sundials_objects = _build_clib(sundials_sources, include_dirs_c, lib_dir, extra_compile_args_c)
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/site-packages/pystan/model.py", line 95, in _build_clib
    build_clibrary.run()
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/distutils/command/build_clib.py", line 115, in run
    self.build_libraries(self.libraries)
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/site-packages/pystan/model.py", line 59, in _build_libraries
    objects = self.compiler.compile(sources,
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/gideonidumah/opt/anaconda3/envs/cloudwalker/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' terminated by signal 6
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

#### Expected Output:
Describe what you expect the output to be. Knowing the correct behavior is also very useful.

#### Python Version:
3.8.3

#### Operating System:
macOS Catalina Version 10.15.5

**Comment by ahartikainen** [comment]
Hi,

can you add `verbose=True`

`sm = pystan.StanModel(model_code=model, verbose=True)`
