### ISSUE TITLE
DistutilsExecError: command 'gcc' failed with exit status 1. Pystan on Google Cloud via Docker Image.

### ISSUE THREAD

**Issue by Sterls** [stan-dev/pystan2#725]
#### Summary:
I had a basic pystan model being trained on Google App Engine successfully. Something changed on GCP on Friday 25th Sept and since then, I've been getting the error DistutilsExecError: command 'gcc' failed with exit status 1. I tested this multiple times, with multiple models and the code that worked before 25-09-2020 doesn't work after that date. The only change I can find is python 3.8.6 was launched but I don't think this is the problem. 

I am using Flask and Pystan within a docker image. 

Using Flask only (localhost) : Success.
Using Docker image only (localhost) : Success
Local environment: Python 3.7, 3.8.3, 3.8.6, GCC 9, GCC 10.0.1

Using Docker image on GCP : Fail. 
Environment: Python 3.7, 3.8.3, 3.8.6, GCC 8.3.0.

`Traceback (most recent call last): File "/usr/local/lib/python3.8/distutils/unixccompiler.py", line 117, in _compile self.spawn(compiler_so + cc_args + [src, '-o', obj] + File "/usr/local/lib/python3.8/distutils/ccompiler.py", line 910, in spawn spawn(cmd, dry_run=self.dry_run) File "/usr/local/lib/python3.8/distutils/spawn.py", line 36, in spawn _spawn_posix(cmd, search_path, dry_run=dry_run) File "/usr/local/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix raise DistutilsExecError( distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1`

**Dockerfile**

```
FROM python:3.7
WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt --> (numpy, pystan, flask...)
ENTRYPOINT ["python"]
CMD ["app.py"]
```

I've used many Dockerfiles. Some include the following:

```
RUN apt-get update && apt-get upgrade -y && apt-get clean
RUN apt-get -y install build-essential 
```

`RUN apt-get --assume-yes install tmux build-essential gcc g++ make binutils `

```
RUN apt-get update
RUN apt-get -y upgrade
RUN apt install -y software-properties-common ca-certificates wget curl ssh
RUN apt install -y build-essential
```

`RUN apt-get update && apt-get install -y gcc-10`

```
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-get update
RUN apt-get install gcc-10 g++-10
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
```

All of my changes to the Dockerfile involves trying to upgrade GCC. Even after adding the necessary lines in the Dockerfile to allow "add-apt-repository" etc etc when I try to install or upgrade to GCC 9 or 10, the docker build failes  because it can't find the package etc.  

Is there something obvious I'm missing? 

I didn't share the pystan code because I'm certain that is not the problem. I tried multiple minimal examples from online that all work locally via flask and docker image but all give the same error on GCP.

**Comment by ahartikainen** [comment]
Can you try building your model with `verbose=True` if there is some C++ error.

How much do you have memory (RAM). Maybe something has changed and compilation needs a bit more memory. PyStan needs somewhere between 2 and 4 GB at the compilation step (building the model).

Try to add this to your model building

    extra_compile_args=["-flto"]

**Comment by Sterls** [comment]
I increased the compute resources to a few CPUs and 30 GB RAM. This did not change the outcome.

EDIT: _I increased the compute-engine resources for the project which was not used at all in the work flow. It was run on app engine so compute engine resources aren't related to the environment that runs the model._

I set verbose = True and extra_compile_args=["-flto"]. 

GCP logs printed the following:

```
OS: linux, Python: 3.7.9 (default, Sep 10 2020, 17:09:36) 
[GCC 8.3.0], Cython 0.29.21
```

```
Exception on /train [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/local/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/local/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 145, in train
    sm = pystan.StanModel(model_code=line_code.format(**linedict), extra_compile_args=["-flto"],verbose=True);
  File "/usr/local/lib/python3.7/site-packages/pystan/model.py", line 378, in __init__
    build_extension.run()
  File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/local/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1
```

Does this offer you any additional information?

**Comment by Sterls** [comment]
Also, when I run it locally, here is some of the output. **Keep in mind that when I run locally, there is no problem.**

```
/home/sterls/.local/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/Product.h:132:22:   required from ‘Eigen::internal::dense_product_base<Lhs, Rhs, Option, 6>::operator const Scalar() const [with Lhs = Eigen::Product<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, 1, -1> >, const Eigen::Transpose<Eigen::Matrix<double, -1, 1> > >, Eigen::Matrix<double, -1, -1>, 0>; Rhs = Eigen::Matrix<double, -1, 1>; int Option = 0; Eigen::internal::dense_product_base<Lhs, Rhs, Option, 6>::Scalar = double]’
/home/sterls/.local/lib/python3.8/site-packages/pystan/stan/src/stan/mcmc/hmc/hamiltonians/dense_e_metric.hpp:24:60:   required from ‘double stan::mcmc::dense_e_metric<Model, BaseRNG>::T(stan::mcmc::dense_e_point&) [with Model = anon_model_1cb259321be2191dc840148a0535c3e6_namespace::anon_model_1cb259321be2191dc840148a0535c3e6; BaseRNG = boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014, 0, 2147483563>, boost::random::linear_congruential_engine<unsigned int, 40692, 0, 2147483399> >]’
/home/sterls/.local/lib/python3.8/site-packages/pystan/stan/src/stan/mcmc/hmc/hamiltonians/dense_e_metric.hpp:23:14:   required from here
/home/sterls/.local/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/AssignEvaluator.h:86:63: warning: enum constant in boolean context [-Wint-in-bool-context]
   86 |     MayLinearVectorize = bool(MightVectorize) && MayLinearize && DstHasDirectAccess
      |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
In file included from /home/sterls/.local/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Core:420,
                 from /home/sterls/.local/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/Dense:1,
                 from /home/sterls/.local/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat/meta/as_array_or_scalar.hpp:4,
                 from /home/sterls/.local/lib/python3.8/site-packages/pystan/stan/lib/stan_math/stan/math/prim/mat.hpp:9,
                 from /home/sterls/.local/lib/python3.8/site-packages/pystan/stan/src/stan/io/dump.hpp:6,
                 from /home/sterls/.local/lib/python3.8/site-packages/pystan/py_var_context.hpp:12,
                 from /tmp/pystan_xxvg1evp/stanfit4anon_model_1cb259321be2191dc840148a0535c3e6_5317563502637311554.cpp:703:
/home/sterls/.local/lib/python3.8/site-packages/pystan/stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/AssignEvaluator.h:90:50: warning: enum constant in boolean context [-Wint-in-bool-context]
   90 |     MaySliceVectorize  = bool(MightVectorize) && bool(DstHasDirectAccess)
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /tmp/pystan_xxvg1evp/tmp/pystan_xxvg1evp/stanfit4anon_model_1cb259321be2191dc840148a0535c3e6_5317563502637311554.o -o /tmp/pystan_xxvg1evp/stanfit4anon_model_1cb259321be2191dc840148a0535c3e6_5317563502637311554.cpython-38-x86_64-linux-gnu.so
```

I use sub-par (small in value) parameters for the model to compile and fit quickly so I can continue with testing the workflow.

**Comment by ahartikainen** [comment]
That later msg are what I'm looking for. I wonder if Google Cloud somehow removes those?

Can you try the following with `verbose=True`

    python myscript.py > output.txt

Also, do you import any packages before compilation?

**Comment by Sterls** [comment]
**app.py** built from a tutorial I found online. This works locally via flask as well as local docker image.

```
from __future__ import print_function, division

import os
import sys
import numpy as np

import pystan

import pickle

from createdate import *

from flask import Flask
from flask import request

app = Flask(__name__)
logger = logging.getLogger('werkzeug') 
handler = logging.FileHandler('test.log') 
logger.addHandler(handler) 

@app.route('/')
def main():
	logger.info("This is main")
	return 'Container is up and running again'
	
	
@app.route('/train')
def train():
	# Create model code
	line_code = """
	data {{
	    int<lower=0> N;      
	    real y[N];           
	    real x[N];          
	    real<lower=0> sigma;
	}}
	parameters {{
	    // parameters for the fit
	    real m;
	    real c;
	}}
	transformed parameters {{
	    real theta[N];
	    for (j in 1:N)
	    theta[j] = m * x[j] + c; 
	}}
	model {{
	    m ~ normal({mmu}, {msigma});    
	    c ~ uniform({clower}, {cupper}); 
	    y ~ normal(theta, sigma);        
	}}
	"""

	# set the data and the abscissa
	linear_data = {'N': M,         
		       'y': data,        
		       'x': x,          
		       'sigma': sigma} 

	Nsamples = 10 # set the number of iterations of the sampler
	chains = 2      # set the number of chains to run with

	# dictionary for inputs into line_code
	linedict = {}
	linedict['mmu'] = 0.0   
	linedict['msigma'] = 10  
	linedict['clower'] = -10 
	linedict['cupper'] = 10  
	logger.info("Training starting")

	sm = pystan.StanModel(model_code=line_code.format(**linedict), extra_compile_args=["-flto"],verbose=True)
	
	logger.info("Model created")
	
	fit = sm.sampling(data=linear_data, iter=Nsamples, chains=chains)
	
	logger.info("Model fitted")

	with open('model_dict.pickle', "wb") as f:		
		pickle.dump({"model" : sm, "fit" : fit}, f)
		
	logger.info("model dict pickled")

	return 'Model trained!'


if __name__ == '__main__':
	from waitress import serve
	serve(app, host='0.0.0.0', port=8080)
```

**Dockerfile**

```
FROM python:latest
WORKDIR /app
COPY . /app
RUN apt-get update && apt-get upgrade -y && apt-get -y install build-essential
RUN apt-get update && apt-get upgrade -y && apt-get install -y gcc
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
```

**requirements.txt**

```
numpy
pystan
flask
waitress
google-cloud-storage
google-cloud-logging
```

**Relevant (I think) gitlab CI output when compiling the project:**
GCC 8.3 is not the latest. 

```
Step 5/9 : RUN apt-get update && apt-get upgrade -y && apt-get install -y gcc
 ---> Running in 07592603d8d3
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
gcc is already the newest version (4:8.3.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Working on the output.txt file for you now.

**Comment by ahartikainen** [comment]
I wonder if you also need to install g++ ( I think build-essential will install it )

Can you try this

https://gist.github.com/ahartikainen/06192df9719031cf1a22b887b7b5d67b

but change model line to 

    stan_model, cpp_output = capture_output(pystan.StanModel, model_code=stan_code)

and print it if there is something

**Comment by Sterls** [comment]
**Output.txt when run locally**

[output.txt](https://github.com/stan-dev/pystan/files/5298456/output.txt)

**Comment by ahartikainen** [comment]
It works locally.

**Comment by Sterls** [comment]
I'm trying to figure out how to get the output from GCP. When I commit/push gitlab CI creates a docker image and deploys it to google app engine. Here is where I get a link and run URL/train. I'm looking around the cloud logs to find what you're asking for. I made the changes you shared earlier.

**Comment by Sterls** [comment]
**Solution**

In the yaml file, I had to use manual scaling to increase the resources. I don't know why Google App Engine stopped the most basic model from running on a flex environment. There was no indication that it was running out of resources.

app.yaml
```
runtime: custom
env: flex
service: pystan-model

manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 6
  disk_size_gb: 50
```

Sorry to waste your time.

**Comment by ahartikainen** [comment]
Haha, no time wasted. Great to hear that you had your problem solved.
