### ISSUE TITLE
Error running Eight Schools example

### ISSUE THREAD

**Issue by leoguelman** [stan-dev/pystan2#748]
I'd appreciate any pointers to fix the error getting below when running Eight Schools:

```python
>>> fit = sm.sampling(data=schools_dat, iter=1000, chains=4)
Process SpawnPoolWorker-1:
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1184497513344622333'
ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1184497513344622333'
Traceback (most recent call last):
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1184497513344622333'
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/lguelman/opt/anaconda3/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
ModuleNotFoundError: No module named 'stanfit4anon_model_19a09b474d1901f191444eaf8a6b8ce2_1184497513344622333'
```

## System
macOS Big Sur 11.2

**Comment by ahartikainen** [comment]
before sampling call

```
import multiprocessing
multiprocessing.set_start_method("fork")
```

**Comment by leoguelman** [comment]
That worked, thanks!

**Comment by smoh** [comment]
Hi, I think I am encountering this issue trying to set up a fresh conda environment on mac osx Big Sur 11.2.2. I have just found this thread and found that the eight schools example works with 
```python
import multiprocessing
multiprocessing.set_start_method("fork")
```
added but could you give me some explanation as to why that is? What changed?

**Comment by ahartikainen** [comment]
Hi, here are couple of links

https://stackoverflow.com/questions/65098398/why-using-fork-works-but-using-spawn-fails-in-python3-8-multiprocessing

https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods
